# Python Syntax: Medical Insurance Project

## Syntax and Variable Types:

Suppose you are a medical professional curious about how certain factors contribute to medical insurance costs. Using a formula that estimates a person's yearly insurance costs, you will investigate how different factors such as age, sex, BMI, etc. affect the prediction.

## Setting up Factors

1. Our first step is to create the variables for each factor we will consider when estimating medical insurance costs.

   These are the variables we will need to create:
   - `age`: age of the individual in years
   - `sex`: 0 for female, 1 for male*
   - `bmi`: individual's body mass index
   - `num_of_children`: number of children the individual has
   - `smoker`: 0 for a non-smoker, 1 for a smoker
   
   In the code block below, create the following variables for a **28**-year-old, **nonsmoking woman** who has **three children** and a **BMI** of **26.2**.
   
   **Note**: We are using this [medical insurance dataset](https://www.kaggle.com/mirichoi0218/insurance) as a guide, which unfortunately does not include data for non-binary individuals.

In [6]:
# initializing variables
age=28
sex=0
bmi=26.2
num_of_children=3
smoker=0

## Working with the Formula

2. After the declaration of the variables, create a variable called `insurance_cost` that utilizes the following formula:

   $$
   \begin{aligned}
   insurance\_cost = 250*age - 128*sex \\
   + 370*bmi + 425*num\_of\_children \\
   + 24000*smoker - 12500 \\
   \end{aligned}
   $$

In [12]:
# insurance formula written out
insurance_cost=250*age-128*sex+370*bmi+425*num_of_children+24000*smoker-12500

3. Let's display this value in an informative way. Print out the following string in the kernel:

   ```
   This person's insurance cost is {insurance_cost} dollars.
   ```
   
   You will need to use string concatenation, including the `str()` function to print out the `insurance_cost`.

In [15]:
# print out the insurance cost
print("This person's insurance cost is " +str(insurance_cost)+ "dollars.")

This person's insurance cost is 5469.0dollars.


## Looking at Age Factor

4. We have seen how our formula can estimate costs for one individual. Now let's play with some individual factors to see what role each one plays in our estimation!

   Let's start with the `age` factor. Using a plus-equal operator, add 4 years to our `age` variable.

In [19]:
# add 4 years to age
age +=4

5. Now that we have changed our `age` value, we want to recalculate our insurance cost. Declare a new variable called `new_insurance_cost` in the code block below.

   Make sure you leave the `insurance_cost` variable the same as in Task 2. We will use it later in our program!

In [22]:
# calculate the new insurance cost
new_insurance_cost=250*age-128*sex+370*bmi+425*num_of_children+24000*smoker-12500
print("This person's new insurance cost is " +str(new_insurance_cost)+ "dollars.")

This person's new insurance cost is 6469.0dollars.


6. Next, we want to find the difference between our `new_insurance_cost` and `insurance_cost`. To do this, let's create a new variable called `change_in_insurance_cost` and set it equal to the difference between `new_insurance_cost` and `insurance_cost`.

   Note: depending on the order that we subtract (eg., `new_insurance_cost - insurance_cost` vs. `insurance_cost - new_insurance_cost`), we'll get a positive or negative version of the same number. To make this difference interpretable, let's calculate `new_insurance cost - insurance_cost`. Then we can say, "people who are four years older have estimated insurance costs that are `change_in_insurance_cost` dollars different, where the sign of `change_in_insurance_cost` tells us whether the cost is higher or lower".

7. We want to display this information in an informative way similar to the output from instruction 3. In the code block below, print the following string, where `XXX` is replaced by the value of `change_in_insurance_cost`:

   ```
   The change in cost of insurance after increasing the age by 4 years is XXX dollars.
   ```
   
   Doing this will tell us how 4 years in age affects medical insurance cost estimates assuming that all other variables remain the same.
   
   You will need to concatenate strings and use the `str()` method.

In [30]:
change_in_insurance_cost=new_insurance_cost-insurance_cost
print("The change in cost of insurance after increasing the age by 4 years is " +str(change_in_insurance_cost)+ "dollars.")

The change in cost of insurance after increasing the age by 4 years is 1000.0dollars.


## Looking at BMI Factor

8. Now that you have looked at the age factor, let's move onto another one: BMI. First, we have to redefine our `age` variable to be its original value.

   Set `age` to `28`. This will reset its value and allow us to focus on just the change in the BMI factor moving forward.
   
   On the next line, using the plus-equal operator, add `3.1` to our `bmi` variable.

In [34]:
age=28
# add 3.1 to bmi
bmi+=3.1

9. Now let's find out how a change in BMI affects insurance costs. Our next steps are pretty much the same as we have done before when looking at `age`.
   1. Below the line where `bmi` was increased by `3.1`, rewrite the insurance cost formula and assign it to the variable name `new_insurance_cost`.
   2. Save the difference between `new_insurance_cost` and `insurance_cost` in a variable called `change_in_insurance_cost`.
   3. Display the following string in the output terminal, where `XXX` is replaced by the value of `change_in_insurance_cost`:
   
   ```py
   The change in estimated insurance cost after increasing BMI by 3.1 is XXX dollars.
   ```

In [37]:
new_insurance_cost=250*age-128*sex+370*bmi+425*num_of_children+24000*smoker-12500
change_in_insurance_cost=new_insurance_cost-insurance_cost
print("The change in estimated insurance cost after increasing BMI by 3.1 is "+str(change_in_insurance_cost)+ "dollars.")

The change in estimated insurance cost after increasing BMI by 3.1 is 1147.0dollars.


## Looking at Male vs. Female Factor

10. Let's look at the effect sex has on medical insurance costs. Before we make any additional changes, first reassign your `bmi` variable back to its original value of `26.2`.

    On a new line of code in the code block below, reassign the value of `sex` to `1`. A reminder that `1` identifies male individuals and `0` identifies female individuals.

In [41]:
bmi=26.2
# male vs. female factor
# change value of sex to 1
sex=1

11. Perform the steps below!
    1. Rewrite the insurance cost formula and assign it to the variable name `new_insurance_cost`.
    2. Save the difference between `new_insurance_cost` and `insurance_cost` in a variable called `change_in_insurance_cost`.
    3. Display the following string, where `XXX` is replaced by the value of `change_in_insurance_cost`:
    ```
    The change in estimated cost for being male instead of female is XXX dollars.
    ```

In [44]:
new_insurance_cost=250*age-128*sex+370*bmi+425*num_of_children+24000*smoker-12500
change_in_insurance_cost=new_insurance_cost-insurance_cost
print("The change in estimated cost for being male instead of female is "+str(change_in_insurance_cost)+ "dollars.")

The change in estimated cost for being male instead of female is -128.0dollars.


12. Notice that this time you got a negative value for `change_in_insurance_cost`. Let's think about what that means. We changed the sex variable from `0` (female) to `1` (male) and it decreased the estimated insurance costs.

    This means that men tend to have lower medical costs on average than women. Reflect on the other findings you have dug up from this investigation so far.

## Looking at Smoking Factor

So far we have looked at 3 of the 5 factors in the insurance costs formula. Now we see the `smoker`.
1. Rewrite the insurance cost formula and assign it to the variable name `new_insurance_cost`.
2. Save the difference between `new_insurance_cost` in a variable called `change_in_insurance_cost`.
3. Display the information below!

In [51]:
sex=0
smoker=1

In [53]:
new_insurance_cost=250*age-128*sex+370*bmi+425*num_of_children+24000*smoker-12500
change_in_insurance_cost=new_insurance_cost-insurance_cost
print("The change in estimated cost for being smoker instead of non smoker is "+str(change_in_insurance_cost)+ "dollars.")

The change in estimated cost for being smoker instead of non smoker is 24000.0dollars.


## Functions:

In this code, we estimate the medical insurance costs for two individuals, Maria and Omar, based on five variables:
These variables are used in the following formula to estimate an individual’s insurance cost (in USD):
   - `age`: age of the individual in years
   - `sex`: 0 for female, 1 for male*
   - `bmi`: individual's body mass index
   - `num_of_children`: number of children the individual has
   - `smoker`: 0 for a non-smoker, 1 for a smoker

 $$
   \begin{aligned}
   insurance\_cost = 250*age - 128*sex \\
   + 370*bmi + 425*num\_of\_children \\
   + 24000*smoker - 12500 \\
   \end{aligned}
   $$

In [60]:
# defining a function called calculate_insurance_cost()
def calculate_insurance_cost(name,age,sex,bmi,num_of_children,smoker):
  estimated_cost=250*age - 128*sex + 370*bmi + 425*num_of_children + 24000*smoker - 12500
  print("The estimated insurance cost for " +name+" is " +str(estimated_cost)+ " dollars.")
  return estimated_cost  #Return estimated_cost



# Estimate Maria's insurance cost
maria_insurance_cost = calculate_insurance_cost("maria",28,0,26.2,3,0) #Calling a function

# Estimate Omar's insurance cost 
omar_insurance_cost = calculate_insurance_cost("Omar",35,1,22.2,0,1) #Calling a function

#function to calculate the difference between the insurance costs
def diff_insurance_cost(maria_insurance_cost,omar_insurance_cost):
  difference=maria_insurance_cost-omar_insurance_cost
  print("The difference in insurance cost is " +str(difference)+ " dollars.")
diff_insurance_cost(maria_insurance_cost,omar_insurance_cost)

The estimated insurance cost for maria is 5469.0 dollars.
The estimated insurance cost for Omar is 28336.0 dollars.
The difference in insurance cost is -22867.0 dollars.


## Control Flow:

The function estimate_insurance_cost() estimates the medical insurance cost for an individual, based on four variables:

   - `age`: age of the individual in years
   - `sex`: 0 for female, 1 for male*
   - `num_of_children`: number of children the individual has
   - `smoker`: 0 for a non-smoker, 1 for a smoker


insurance_cost=400∗age−128∗sex+425∗num_of_children+1000∗smoker-2500

In general, insurance costs are higher for smokers. We can use data from the smoker variable to provide advice on how to lower insurance costs.define a function called `analyze_smoker()` that takes an input smoker_status.

Inside of the `analyze_smoker()` function,
If `smoker_status` is equal to 1, print` "To lower your cost, you should consider quitting smoking."`
Otherwise, print` "Smoking is not an issue for you.`"

In [87]:
def analyze_smoker(smoker_status):
  if smoker_status==1:
    print("To lower your cost, you should consider quitting smoking.")
  else:
    print("Smoking is not an issue for you.")

Now that we’ve written the analyze_smoker() function, let’s make use of it.

In the `estimate_insurance_cost()` function, go to the line of code that prints the estimated insurance cost. On the next line, make a function call to `analyze_smoker()` , passing in the `smoker` variable as an argument.smokert.t.

In [97]:
# Function to estimate insurance cost:
def estimate_insurance_cost(name, age, sex, num_of_children, smoker):
  estimated_cost = 400*age - 128*sex + 425*num_of_children + 10000*smoker - 2500
  print(name + "'s Estimated Insurance Cost: " + str(estimated_cost) + " dollars.")
  analyze_smoker(smoker)
  return estimated_cost
 
# Estimate Keanu's insurance cost
keanu_insurance_cost = estimate_insurance_cost(name = 'Keanu', age = 29, sex = 1, num_of_children = 3, smoker = 1)


Keanu's Estimated Insurance Cost: 20247 dollars.
To lower your cost, you should consider quitting smoking.


## Lists

In this , you will examine how factors such as age, sex, BMI, number of children, and smoking status contribute to medical insurance costs.

You will apply your new knowledge of Python Lists to store insurance cost data in a list as well as compare **estimated** insurance costs to **actual** insurance costs.

Let's get started!

### Creating a List

1. First, take a look at the code in the code block below.

   The function `estimate_insurance_cost()` estimates the medical insurance cost for an individual, based on five variables:
   - `age`: age of the individual in years
   - `sex`: 0 for female, 1 for male
   - `bmi`: individual's body mass index
   - `num_of_children`: number of children the individual has
   - `smoker`: 0 for a non-smoker, 1 for a smoker
   
   These variables are used in the following formula to estimate an individual's insurance cost (in USD):
   
   $$
   insurance\_cost = 250*age - 128*sex + 370*bmi + 425*num\_of\_children + 24000*smoker - 12500
   $$
   
   Observe below the code the estimated insurance costs for three individuals - Maria, Rohan, and Valentina.

In [62]:
def estimate_insurance_cost(name, age, sex, bmi, num_of_children, smoker):
  estimated_cost = 250*age - 128*sex + 370*bmi + 425*num_of_children + 24000*smoker - 12500
  print(name + "'s Estimated Insurance Cost: " + str(estimated_cost) + " dollars.")
  return estimated_cost
 
# Estimate Maria's insurance cost
maria_insurance_cost = estimate_insurance_cost(name = "Maria", age = 31, sex = 0, bmi = 23.1, num_of_children = 1, smoker = 0)

# Estimate Rohan's insurance cost
rohan_insurance_cost = estimate_insurance_cost(name = "Rohan", age = 25, sex = 1, bmi = 28.5, num_of_children = 3, smoker = 0)

# Estimate Valentina's insurance cost
valentina_insurance_cost = estimate_insurance_cost(name = "Valentina", age = 53, sex = 0, bmi = 31.4, num_of_children = 0, smoker = 1)

Maria's Estimated Insurance Cost: 4222.0 dollars.
Rohan's Estimated Insurance Cost: 5442.0 dollars.
Valentina's Estimated Insurance Cost: 36368.0 dollars.


2. We want to compare the estimated insurance costs (as calculated by our function) to the actual amounts that Maria, Rohan, and Valentina paid.

   Create a list called `names` and fill it with the names of individuals you are estimating insurance costs for:
   - `"Maria"`
   - `"Rohan"`
   - `"Valentina"`

In [65]:
names=["Maria","Rohan","Valentina"]

3. Next, create a list called `insurance_costs` and fill it with the actual amounts that Maria, Rohan, and Valentina paid for insurance:
   - `4150.0`
   - `5320.0`
   - `35210.0`

In [130]:
insurance_costs=[4150.0,5320.0,35210.0]
names.append("Akira")
insurance_costs.append(2930.0)

### Combining Lists

4. Currently the `names` and `insurance_costs` lists are separate, but we want each name to be paired with an insurance cost.

   Create a new variable called `insurance_data` that combines `names` and `insurance_costs` using the `zip()` function.
   
   Print this new variable.

5. The output should look something like:

   ```
   <zip object at 0x7f1631e86b48>
   ```
   
   This output does not mean much to us. To change it to a format we can actually understand, we must convert the `zip` object to a list by doing the following:
   
   ```
   list(zip(____, ____))
   ```
   
   Convert the `insurance_data` object to a list using this method. Run the code to see the result - you should now see a list of names and insurance costs.

In [135]:
insurance_data=list(zip(names,insurance_costs))
print(insurance_data)

[('Maria', 4150.0), ('Rohan', 5320.0), ('Valentina', 35210.0), ('Akira', 2930.0)]


### Appending to a List

6. Next, create an empty list called `estimated_insurance_data`.

   This is the list we'll use to store the estimated insurance costs for our three individuals.

In [139]:
estimated_insurance_data = []

7. We want to add our estimated insurance data for Maria, Rohan, and Valentina to the `estimated_insurance_data` list.

   Use `.append()` to add `("Maria", maria_insurance_cost)` to `estimated_insurance_data`. Do the same for Rohan and Valentina.

In [142]:
estimated_insurance_data.append(("Maria", maria_insurance_cost))
estimated_insurance_data.append(("Rohan", rohan_insurance_cost))
estimated_insurance_data.append(("Valentina", valentina_insurance_cost))

8. Print `estimated_insurance_data`.

   Make sure the output is what you expected.

In [145]:
print(estimated_insurance_data)

[('Maria', 4222.0), ('Rohan', 5442.0), ('Valentina', 36368.0)]


### Inspecting the data

9. In the output, you should see two lists. The first one represents the **actual** insurance cost data and the second one represents the **estimated** insurance cost data.

   However, it's difficult to know this just by looking at the output. As a data scientist, you want to make sure that your data is clean and easy to understand.
   
   Add to the print statement for `insurance_data` so that it's clear what the list contains. The output of the print statement should look like:
   
   ```
   Here is the actual insurance cost data: [...list output...]
   ```

In [155]:
print("Here is the actual insurance cost data: " + str(insurance_data))

Here is the actual insurance cost data: [('Maria', 4150.0), ('Rohan', 5320.0), ('Valentina', 35210.0), ('Akira', 2930.0)]


10. Do the same for the print statement that prints `estimated_insurance_data`. The output should look like:

   ```
   Here is the estimated insurance cost data: [...list output...]
   ```

In [152]:
print("Here is the estimated insurance cost data: " + str(estimated_insurance_data))

Here is the estimated insurance cost data: [('Maria', 4222.0), ('Rohan', 5442.0), ('Valentina', 36368.0)]


11. See the results from both tasks above.

    It should be much more clear from the output what each of the two lists represents, helping you better understand the data you're working with.
    
    You may notice that there are differences between the actual insurance costs and estimated insurance costs. This means that our `estimate_insurance_cost()` function does not calculate insurance costs with 100% accuracy.
    
    Compare the estimated insurance data to the actual insurance data. Do the estimated insurance costs seem to be overestimated or underestimated?

12. Congratulations! In this project, you used Python lists to store **estimated** insurance cost data and then compare that data to **actual** insurance cost data.

    As you've seen, lists are data structures in Python that can contain multiple pieces of data in a single object. As a data scientist, you'll find yourself working with this data structure quite often. You now have a solid foundation to move forward in your data science journey!
    
    If you'd like additional practice on lists, here are some ways you might extend this project:
    - Estimate the insurance cost for a new individual, Akira, who is a 19-year-old male non-smoker with no children and a BMI of 27.1. Make sure to append his name to `names` and his actual insurance cost, `2930.0`, to `insurance_costs`.
    

In [158]:
akira_insurance_cost=estimate_insurance_cost(name="Akira", age=19, sex=1, bmi=27.1, num_of_children=0, smoker=0)
estimated_insurance_data.append(("Akira", akira_insurance_cost))
print("Here is the actual insurance cost data: " + str(insurance_data))
print("Here is the estimated insurance cost data: " + str(estimated_insurance_data))

Akira's Estimated Insurance Cost: 2149.0 dollars.
Here is the actual insurance cost data: [('Maria', 4150.0), ('Rohan', 5320.0), ('Valentina', 35210.0), ('Akira', 2930.0)]
Here is the estimated insurance cost data: [('Maria', 4222.0), ('Rohan', 5442.0), ('Valentina', 36368.0), ('Akira', 2149.0)]


Working with Python Lists

## Exploring List Data

1. First, take a look at the two lists in the code block below.

   The list `names` stores the names of ten individuals, and `insurance_costs` stores their medical insurance costs.
   
   Let's add additional data to these lists:
   - Append a new individual, `"Priscilla"`, to `names`.
   - Append her insurance cost, `8320.0` to `insurance_costs`.

In [163]:
names = ["Mohamed", "Sara", "Xia", "Paul", "Valentina", "Jide", "Aaron", "Emily", "Nikita", "Paul"]
insurance_costs = [13262.0, 4816.0, 6839.0, 5054.0, 14724.0, 5360.0, 7640.0, 6072.0, 2750.0, 12064.0]

In [165]:
names.append("Prisilla")
insurance_costs.append(8320.0)

2. Currently, the `names` and `insurance_costs` lists are separate, but we want each insurance cost to be paired with a name.

   Create a new variable called `medical_records` that combines `insurance_costs` and `names` into a list using the `zip()` function.
   
   The list should have the following structure:
   
   ```py
   [(cost_0, name_0), (cost_1, name_1), (cost_2, name_2), ...]
   ```

3. Print out `medical_records` below, and make sure the output is what you expected.

In [170]:
medical_records=list(zip(insurance_costs, names))
print(medical_records)

[(13262.0, 'Mohamed'), (4816.0, 'Sara'), (6839.0, 'Xia'), (5054.0, 'Paul'), (14724.0, 'Valentina'), (5360.0, 'Jide'), (7640.0, 'Aaron'), (6072.0, 'Emily'), (2750.0, 'Nikita'), (12064.0, 'Paul'), (8320.0, 'Prisilla')]


4. Let's explore our medical data.

   We want to see how many medical records we are dealing with. Create a variable called `num_medical_records` that stores the length of `medical_records`.

5. Print `num_medical_records` with the following message:

   ```
   There are {number of medical records} medical records.
   ```

In [174]:
num_medical_records=len(medical_records)
print("There are "+str(num_medical_records)+ " medical records." )

There are 11 medical records.


### Selecting List Elements

6. Select the first medical record in `medical_records`, and save it to a variable called `first_medical_record`.

7. Print `first_medical_record` with the following message:

   ```
   Here is the first medical record: {first medical record}
   ```    

In [180]:
first_medical_record=medical_records[0]
print(first_medical_record)

(13262.0, 'Mohamed')


### Sorting Lists

8. Sort `medical_records` so that the individuals with the lowest insurance costs appear at the start of the list.

   Print the sorted `medical_records` with the following message:
   
   ```
   Here are the medical records sorted by insurance cost: {sorted list}
   ```

In [185]:
medical_records.sort()
print("Here are the medical records sorted by insurance cost: " +str(medical_records))

Here are the medical records sorted by insurance cost: [(2750.0, 'Nikita'), (4816.0, 'Sara'), (5054.0, 'Paul'), (5360.0, 'Jide'), (6072.0, 'Emily'), (6839.0, 'Xia'), (7640.0, 'Aaron'), (8320.0, 'Prisilla'), (12064.0, 'Paul'), (13262.0, 'Mohamed'), (14724.0, 'Valentina')]


### Slicing Lists

9. Let's look at the three cheapest insurance costs in our medical records.

   Slice the `medical_records` list, and store the three cheapest insurance costs in a list called `cheapest_three`.


10. Print `cheapest_three` with the following message:

    ```py
    Here are the three cheapest insurance costs in our medical records: {cheapest three}
    ```

In [191]:
cheapest_three=medical_records[:3]
print("Here are the three cheapest insurance costs in our medical records " + str(cheapest_three))

Here are the three cheapest insurance costs in our medical records [(2750.0, 'Nikita'), (4816.0, 'Sara'), (5054.0, 'Paul')]


11. Let's look at the three most expensive insurance costs in our medical records.

    Slice the `medical_records` list, and store the three most expensive insurance costs in a list called `priciest_three`.


12. Print `priciest_three` with the following message:

    ```
    Here are the three most expensive insurance costs in our medical records: {priciest three}
    ```

In [194]:
priciest_three=medical_records[-3:]
print("Here are the three most expensive insurance costs in our medical records: " + str(priciest_three))

Here are the three most expensive insurance costs in our medical records: [(12064.0, 'Paul'), (13262.0, 'Mohamed'), (14724.0, 'Valentina')]


### Counting Elements in a List

13. Some individuals in our medical records have the same name. For example, the name "Paul" shows up twice.

    Count the number of occurrences of "Paul" in the `names` list, and store the result in a variable called `occurrences_paul`.
    
    Print `occurrences_paul` with the following message:
    
    ```
    There are {occurrences Paul} individuals with the name Paul in our medical records.
    ```

In [198]:
occurrences_paul=names.count("Paul")
print("There are " +str(occurrences_paul)+" individuals with the name Paul in our medical records. ")

There are 2 individuals with the name Paul in our medical records. 


14. If you'd like additional practice on lists, here are some ways you might extend this project:
    - Sort the medical records alphabetically by name. You'll have to create a new list using `zip()` to do this.
    - Select the medical records starting at index `3` and ending at index `7` and save it to a variable called `middle_five_records`.

In [203]:
#Sort the medical records alphabetically by name.
new_medical_records=list(zip(names,insurance_costs))
new_medical_records.sort()
print(new_medical_records)

#Select the medical records starting at index `3` and ending at index `7`
middle_five_records=medical_records[3:8]
print(middle_five_records)

[('Aaron', 7640.0), ('Emily', 6072.0), ('Jide', 5360.0), ('Mohamed', 13262.0), ('Nikita', 2750.0), ('Paul', 5054.0), ('Paul', 12064.0), ('Prisilla', 8320.0), ('Sara', 4816.0), ('Valentina', 14724.0), ('Xia', 6839.0)]
[(5360.0, 'Jide'), (6072.0, 'Emily'), (6839.0, 'Xia'), (7640.0, 'Aaron'), (8320.0, 'Prisilla')]


## Loops

You are interested in analyzing medical insurance cost data efficiently without writing repetitive code.

In this , you will use your new knowledge of Python loops to iterate through and analyze medical insurance cost data.

Let's get started!

### Creating a For Loop

1. First, let's take a look at three lists in the code block below:
   - `names` stores the names of seven individuals.
   - `estimated_insurance_costs` stores the estimated medical insurance costs for the individuals.
   - `actual_insurance_costs` stores the actual insurance costs paid by the individuals.
   
   We want to calculate the average insurance cost each person paid. We'll start by adding up all of the insurance costs.
   
   Create a variable `total_cost` and initialize it to `0`.

In [25]:
names = ["Judith", "Abel", "Tyson", "Martha", "Beverley", "David", "Anabel"]
estimated_insurance_costs = [1000.0, 2000.0, 3000.0, 4000.0, 5000.0, 6000.0, 7000.0]
actual_insurance_costs = [1100.0, 2200.0, 3300.0, 4400.0, 5500.0, 6600.0, 7700.0]

total_cost=0

2. Use a `for` loop to iterate through `actual_insurance_costs` and add each insurance cost to the variable `total_cost`.

In [28]:
for i in actual_insurance_costs:
  total_cost+=i
print(total_cost)

30800.0


3. After the `for` loop, create a variable called `average_cost` that stores the `total_cost` divided by the length of the `actual_insurance_costs` list.
4. Print `average_cost` with the following message:

   ```
   Average Insurance Cost: <average_cost> dollars.
   ```

In [31]:
average_cost = total_cost/len(actual_insurance_costs)
print("Average Insurance Cost: " +str(average_cost)+" dollars.")

Average Insurance Cost: 4400.0 dollars.


### Using Range in Loops

5. For each individual in `names`, we want to determine whether their insurance cost is above or below average.

   Write a `for` loop with variable `i` that goes from `0` to `len(names)`.
   

   
6. Inside of the `for` loop, do the following:
   - Create a variable `name`, which stores `names[i]`.
   - Create a variable `insurance_cost`, which stores `actual_insurance_costs[i]`.
   - Print out the insurance cost for each individual, with the following message:
   ```
   The insurance cost for <name> is <insurance_cost> dollars.
   ```

In [35]:
for i in range(len(names)):
  name=names[i]
  insurance_cost=actual_insurance_costs[i]
  print("The insurance cost for "+name+ " is "+str(insurance_cost)+ "dollars.")

The insurance cost for Judith is 1100.0dollars.
The insurance cost for Abel is 2200.0dollars.
The insurance cost for Tyson is 3300.0dollars.
The insurance cost for Martha is 4400.0dollars.
The insurance cost for Beverley is 5500.0dollars.
The insurance cost for David is 6600.0dollars.
The insurance cost for Anabel is 7700.0dollars.


7. Observe the result above.

   You should see the insurance costs for each of the seven individuals in `names`. The `for` loop iterated through the entire list and printed out the insurance cost for each individual.

### Conditions inside a Loop

8. Inside of the `for` loop, use `if`, `elif`, `else` statements after the `print` statement to check whether the insurance cost is above, below, or equal to the average. Print out messages for each case:
   - When `insurance_cost` is higher than the average, print out the following:
   ```
   The insurance cost for <name> is above average.
   ```
   - When `insurance_cost` is lower than the average, print out the following:
   ```
   The insurance cost for <name> is below average.
   ```
   - Otherwise, print out the following:
   ```
   The insurance cost for <name> is equal to the average.
   ```

In [42]:
for i in range(len(names)):
  name=names[i]
  insurance_cost=actual_insurance_costs[i]
  print("The insurance cost for "+name+ " is "+str(insurance_cost)+ "dollars.")
  if insurance_cost > average_cost:
    print("The insurance cost for "+name+ "is above average")
  elif insurance_cost < average_cost:
    print("The insurance cost for "+name+ "is below average")
  else:
    print("The insurance cost for "+name+ "is equal to the average")

The insurance cost for Judith is 1100.0dollars.
The insurance cost for Judithis below average
The insurance cost for Abel is 2200.0dollars.
The insurance cost for Abelis below average
The insurance cost for Tyson is 3300.0dollars.
The insurance cost for Tysonis below average
The insurance cost for Martha is 4400.0dollars.
The insurance cost for Marthais equal to the average
The insurance cost for Beverley is 5500.0dollars.
The insurance cost for Beverleyis above average
The insurance cost for David is 6600.0dollars.
The insurance cost for Davidis above average
The insurance cost for Anabel is 7700.0dollars.
The insurance cost for Anabelis above average


9. Observe the output above.

   You should see messages indicating the insurance cost for each of the seven individuals and where their insurance cost stands relative to the average.

### Creating a List Comprehension

10. If you look closely at `actual_insurance_costs` and `estimated_insurance_costs`, you will notice that each of the actual insurance costs is 10% higher than the estimated insurance costs.
 
    Using a list comprehension, create a new list called `updated_estimated_costs`, which has each element in `estimated_insurance_costs` multiplied by `11/10`.

11. Print `updated_estimated_costs`.

    You should see that the list now looks the same as `actual_insurance_costs`.

In [48]:
updated_estimated_costs=[cost * 11/10 for cost in estimated_insurance_costs]
print(updated_estimated_costs)

[1100.0, 2200.0, 3300.0, 4400.0, 5500.0, 6600.0, 7700.0]


12. If you'd like extra practice with Python loops:
    - Convert the first `for` loop in the code to a `while` loop.
    - Modify the second `for` loop so that it also calculates how far above or below the average estimated insurance cost is.

In [51]:
total_cost=0
index=0
while index < len(actual_insurance_costs):
  total_cost+=actual_insurance_costs[index]
  index+=1
print(total_cost)

30800.0


In [53]:
for i in range(len(names)):
  name=names[i]
  insurance_cost=estimated_insurance_costs[i]
  print("The insurance cost for "+name+ " is "+str(insurance_cost)+ "dollars.")
  if insurance_cost > average_cost:
    print("The insurance cost for "+name+ "is above average")
  elif insurance_cost < average_cost:
    print("The insurance cost for "+name+ "is below average")
  else:
    print("The insurance cost for "+name+ "is equal to the average")

The insurance cost for Judith is 1000.0dollars.
The insurance cost for Judithis below average
The insurance cost for Abel is 2000.0dollars.
The insurance cost for Abelis below average
The insurance cost for Tyson is 3000.0dollars.
The insurance cost for Tysonis below average
The insurance cost for Martha is 4000.0dollars.
The insurance cost for Marthais below average
The insurance cost for Beverley is 5000.0dollars.
The insurance cost for Beverleyis above average
The insurance cost for David is 6000.0dollars.
The insurance cost for Davidis above average
The insurance cost for Anabel is 7000.0dollars.
The insurance cost for Anabelis above average


## Strings:

You are a doctor who needs to clean up medical patient records, which are currently stored in one large string.

In this project, you will use your new knowledge of Python strings to obtain and clean up medical data so that it is easier to read and analyze.

Let's get started!

### Working with Strings

1. First, take a look at the code in the code block below.

   The string `medical_data` stores the medical records for ten individuals. Each record is separated by a `;` and contains the name, age, BMI (body mass index), and insurance cost for an individual, in that order.
   
   Print `medical_data` to see the output below the code block.

In [64]:
medical_data = \
"""Marina Allison   ,27   ,   31.1 , 
#7010.0   ;Markus Valdez   ,   30, 
22.4,   #4050.0 ;Connie Ballard ,43 
,   25.3 , #12060.0 ;Darnell Weber   
,   35   , 20.6   , #7500.0;
Sylvie Charles   ,22, 22.1 
,#3022.0   ;   Vinay Padilla,24,   
26.9 ,#4620.0 ;Meredith Santiago, 51   , 
29.3 ,#16330.0;   Andre Mccarty, 
19,22.7 , #2900.0 ; 
Lorena Hodson ,65, 33.1 , #19370.0; 
Isaac Vu ,34, 24.8,   #7045.0"""

print(medical_data)

Marina Allison   ,27   ,   31.1 , 
#7010.0   ;Markus Valdez   ,   30, 
22.4,   #4050.0 ;Connie Ballard ,43 
,   25.3 , #12060.0 ;Darnell Weber   
,   35   , 20.6   , #7500.0;
Sylvie Charles   ,22, 22.1 
,#3022.0   ;   Vinay Padilla,24,   
26.9 ,#4620.0 ;Meredith Santiago, 51   , 
29.3 ,#16330.0;   Andre Mccarty, 
19,22.7 , #2900.0 ; 
Lorena Hodson ,65, 33.1 , #19370.0; 
Isaac Vu ,34, 24.8,   #7045.0


2. We want the insurance costs to be represented in US dollars.

   Replace all instances of `#` in `medical_data` with `$`. Store the result in a variable called `updated_medical_data`.
   
   Print `updated_medical_data`.

In [67]:
updated_medical_data=medical_data.replace('#','$')
print(updated_medical_data)

Marina Allison   ,27   ,   31.1 , 
$7010.0   ;Markus Valdez   ,   30, 
22.4,   $4050.0 ;Connie Ballard ,43 
,   25.3 , $12060.0 ;Darnell Weber   
,   35   , 20.6   , $7500.0;
Sylvie Charles   ,22, 22.1 
,$3022.0   ;   Vinay Padilla,24,   
26.9 ,$4620.0 ;Meredith Santiago, 51   , 
29.3 ,$16330.0;   Andre Mccarty, 
19,22.7 , $2900.0 ; 
Lorena Hodson ,65, 33.1 , $19370.0; 
Isaac Vu ,34, 24.8,   $7045.0


3. We want to calculate the number of medical records in our data.

   Create a variable called `num_records` and initialize it at 0.

4. Next, write a `for` loop to iterate through the `updated_medical_data` string. Inside of the loop, add `1` to `num_records` when the current character is equal to `$`.
5. Outside of the loop, print `num_records` with the following message:

   ```
   There are {num_records} medical records in the data.
   ```

In [71]:
num_records=0
for record in updated_medical_data:
  if record == "$":
    num_records += 1
print("There are  {} medical records in the data.".format(num_records))

There are  10 medical records in the data.


### Splitting Strings

6. The medical data in its current form is difficult to analyze. An essential job for a data scientist is to clean up data so that it's easy to work with.

   Let's start off by splitting the `updated_medical_data` string into a list of each record. Remember that each medical record is separated by a `;` in the string.
   
   Store the result in a variable called `medical_data_split` and print this variable.

In [77]:
medical_data_split=updated_medical_data.split(";")
print(medical_data_split)

['Marina Allison   ,27   ,   31.1 , \n$7010.0   ', 'Markus Valdez   ,   30, \n22.4,   $4050.0 ', 'Connie Ballard ,43 \n,   25.3 , $12060.0 ', 'Darnell Weber   \n,   35   , 20.6   , $7500.0', '\nSylvie Charles   ,22, 22.1 \n,$3022.0   ', '   Vinay Padilla,24,   \n26.9 ,$4620.0 ', 'Meredith Santiago, 51   , \n29.3 ,$16330.0', '   Andre Mccarty, \n19,22.7 , $2900.0 ', ' \nLorena Hodson ,65, 33.1 , $19370.0', ' \nIsaac Vu ,34, 24.8,   $7045.0']


7. Our data is now stored in a list, but it is still hard to read. Let's split each medical record into its own list.

   First, define an empty list called `medical_records`.
8. Next, iterate through `medical_data_split` and for each record, split the string after each comma (`,`) and append the split string to `medical_records`.

   Print `medical_records` after the loop.

In [82]:
medical_records=[]
for record in medical_data_split:
  medical_records.append(record.split(","))
print(medical_records)

[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   '], ['Markus Valdez   ', '   30', ' \n22.4', '   $4050.0 '], ['Connie Ballard ', '43 \n', '   25.3 ', ' $12060.0 '], ['Darnell Weber   \n', '   35   ', ' 20.6   ', ' $7500.0'], ['\nSylvie Charles   ', '22', ' 22.1 \n', '$3022.0   '], ['   Vinay Padilla', '24', '   \n26.9 ', '$4620.0 '], ['Meredith Santiago', ' 51   ', ' \n29.3 ', '$16330.0'], ['   Andre Mccarty', ' \n19', '22.7 ', ' $2900.0 '], [' \nLorena Hodson ', '65', ' 33.1 ', ' $19370.0'], [' \nIsaac Vu ', '34', ' 24.8', '   $7045.0']]


### Cleaning Data

9. Our data is now slightly more readable. However, it is not properly formatted - it contains unnecessary whitespace.

   To fix this, let's start by creating an empty list called `medical_records_clean`.
10. Next, use a `for` loop to iterate through `medical_records`.

    Inside of the loop, create an empty list called `record_clean`. We'll use this list to store a formatted version of each medical record.
11. After the `record_clean` variable, create a nested `for` loop that goes through each `record`:

    ```py
    for item in record
    ```
    
    Inside of this loop, append `item.strip()` to `record_clean` to remove any whitespace from the string.

12. Finally, we need to add each cleaned up record to `medical_records_clean`.

    Outside of the nested `for` loop, append `record_clean` to `medical_records_clean`.
13. Print `medical_records_clean` outside of the `for` loops to see the output.

    You should see output that is formatted and much easier to read.

In [94]:
medical_records_clean=[]
for record in medical_records:
  record_clean=[]
  for item in record:
    record_clean.append(item.strip())
  medical_records_clean.append(record_clean)
print(medical_records_clean)

[['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Meredith Santiago', '51', '29.3', '$16330.0'], ['Andre Mccarty', '19', '22.7', '$2900.0'], ['Lorena Hodson', '65', '33.1', '$19370.0'], ['Isaac Vu', '34', '24.8', '$7045.0']]


### Analyzing Data

14. Our data is now clean and ready for analysis.

    For example, to print out the names of each of the ten individuals, we can use the following loop:

In [101]:
for record in medical_records_clean:
  record[0]=record[0].upper()
  print(record[0])

MARINA ALLISON
MARKUS VALDEZ
CONNIE BALLARD
DARNELL WEBER
SYLVIE CHARLES
VINAY PADILLA
MEREDITH SANTIAGO
ANDRE MCCARTY
LORENA HODSON
ISAAC VU


15. Let's store each name, age, BMI, and insurance cost in separate lists.

    To start, create four empty lists:
    - `names`
    - `ages`
    - `bmis`
    - `insurance_costs`

In [106]:
names=[]
ages=[]
bmis=[]
insurance_costs=[]

16. Next, iterate through `medical_records_clean` and for each record:
    - Append the name to `names`.
    - Append the age to `ages`.
    - Append the BMI to `bmis`.
    - Append the insurance cost to `insurance_costs`.
17. Print `names`, `ages`, `bmis`, and `insurance_costs` outside of the loop.

    Make sure the output is what you expect.

In [110]:
for record in medical_records_clean:
  names.append(record[0])
  ages.append(record[1])
  bmis.append(record[2])
  insurance_costs.append(record[3])
print("Names:" +str(names))
print("Ages:"+str(ages))
print("Bmis:"+str(bmis))
print("Insurance costs:"+str(insurance_costs))

Names:['MARINA ALLISON', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'DARNELL WEBER', 'SYLVIE CHARLES', 'VINAY PADILLA', 'MEREDITH SANTIAGO', 'ANDRE MCCARTY', 'LORENA HODSON', 'ISAAC VU']
Ages:['27', '30', '43', '35', '22', '24', '51', '19', '65', '34']
Bmis:['31.1', '22.4', '25.3', '20.6', '22.1', '26.9', '29.3', '22.7', '33.1', '24.8']
Insurance costs:['$7010.0', '$4050.0', '$12060.0', '$7500.0', '$3022.0', '$4620.0', '$16330.0', '$2900.0', '$19370.0', '$7045.0']


18. Now that all of our data is in separate lists, we can easily perform analysis on that data. Let's calculate the average BMI in our dataset.

    First, create a variable called `total_bmi` and set it equal to 0.

In [113]:
total_bmi=0

19. Next, use a `for` loop to iterate through `bmis` and add each `bmi` to `total_bmi`.

    Remember to convert `bmi` to a float.
20. After the for loop, create a variable called `average_bmi` that stores the `total_bmi` divided by the length of the `bmis` list.

    Print out `average_bmi` with the following message:
    ```
    Average BMI: {average_bmi}
    ```

In [116]:
for bmi in bmis:
  total_bmi+=float(bmi)
average_bmi=total_bmi/len(bmis)
print("Average BMI: " ,str(average_bmi))

Average BMI:  25.830000000000002


21. Congratulations! In this , you used Python strings to transform and clean up medical data.
    - Calculate the average insurance cost in `insurance_costs`. You will have the remove the `$` in order to calculate this.
    - Write a for loop that outputs a string for each individual in the following format:
    ```
    Marina is 27 years old with a BMI of 31.1 and an insurance cost of $7010.0.
Markus is 30 years old with a BMI of 22.4 and an insurance cost of $4050.0.
    ...
    ...


In [119]:
total_insurance_costs=0
for cost in insurance_costs:
  total_insurance_costs+=float(cost.replace("$",""))
average_insurance_cost=total_insurance_costs/len(insurance_costs)
print("Average insurance cost is:$"+str(average_insurance_cost))

for record in medical_records_clean:
  print("{} is {} years old with a BMI of {} and an insurance cost of {}".format(record[0],record[1],record[2],record[3]))

Average insurance cost is:$8390.7
MARINA ALLISON is 27 years old with a BMI of 31.1 and an insurance cost of $7010.0
MARKUS VALDEZ is 30 years old with a BMI of 22.4 and an insurance cost of $4050.0
CONNIE BALLARD is 43 years old with a BMI of 25.3 and an insurance cost of $12060.0
DARNELL WEBER is 35 years old with a BMI of 20.6 and an insurance cost of $7500.0
SYLVIE CHARLES is 22 years old with a BMI of 22.1 and an insurance cost of $3022.0
VINAY PADILLA is 24 years old with a BMI of 26.9 and an insurance cost of $4620.0
MEREDITH SANTIAGO is 51 years old with a BMI of 29.3 and an insurance cost of $16330.0
ANDRE MCCARTY is 19 years old with a BMI of 22.7 and an insurance cost of $2900.0
LORENA HODSON is 65 years old with a BMI of 33.1 and an insurance cost of $19370.0
ISAAC VU is 34 years old with a BMI of 24.8 and an insurance cost of $7045.0


## Dictionaries

You have been asked to create a program that organizes and updates medical records efficiently.

In this project, you will use your new knowledge of Python dictionaries to create a database of medical records for patients.

Let's get started!

### Storing Patient Names and Insurance Costs

1. We would like to keep a record of medical patients and their insurance costs.

   First, create an empty dictionary called `medical_costs`.

In [125]:
medical_costs={}

2. Let's populate our `medical_costs` dictionary by adding the following key-value pairs:
   - Add `"Marina"` to `medical_costs` as a key with a value of `6607.0`.
   - Add `"Vinay"` to `medical_costs` as a key with a value of `3225.0`.
   
3. Using one line of code, add the following three patients to the `medical_costs` dictionary:
   - `"Connie"`, with an insurance cost of `8886.0`.
   - `"Isaac"`, with an insurance cost of `16444.0`.
   - `"Valentina"`, with an insurance cost of `6420.0`.
4. Print `medical_costs`. Make sure the dictionary is what you expected.

In [131]:
medical_costs["Marina"]=6607.0
medical_costs["Vinay"]=3225.0
medical_costs.update({"Connie":8886.0,"Isaac":16444.0,"Valentina":6420.0})
print(medical_costs)

{'Marina': 6607.0, 'Vinay': 3225.0, 'Connie': 8886.0, 'Isaac': 16444.0, 'Valentina': 6420.0}


5. You notice that `Vinay`'s insurance cost was incorrectly inputted. Update the value associated with `Vinay` to `3325.0`.

   Print the updated dictionary.

In [134]:
medical_costs["Vinay"]=3325.0
print(medical_costs)

{'Marina': 6607.0, 'Vinay': 3325.0, 'Connie': 8886.0, 'Isaac': 16444.0, 'Valentina': 6420.0}


6. Let's calculate the average medical cost of each patient. Create a variable called `total_cost` and set it equal to 0.

   Next, iterate through the values in `medical_costs` and add each value to the `total_cost` variable.
7. After the loop, create a variable called `average_cost` that stores the `total_cost` divided by the length of the `medical_costs` dictionary.

   Print `average_cost` with the following message:
   
   ```
   Average Insurance Cost: {average_cost}
   ```

In [137]:
total_cost=0
for i in medical_costs.values():
  total_cost+=i
print(total_cost)
average_cost=total_cost/len(medical_costs)
print("Average Insurance Cost: "+str(average_cost))

41682.0
Average Insurance Cost: 8336.4


### List Comprehension to Dictionary

8. You have been asked to create a second dictionary that maps patient names to their ages.

   First, create two lists called `names` and `ages` with the following data:
   
   names | ages
   --- | ---
   Marina | 27
   Vinay | 24
   Connie | 43
   Isaac | 35
   Valentina | 52

In [141]:
names=["Marina","Vinay","Connie","Isaac","Valentina"]
ages=[27,24,43,35,52]

9. Next, create a variable called `zipped_ages` that is a zipped list of pairs between the `names` list and the `ages` list.
10. Create a dictionary called `names_to_ages` by using a list comprehension that iterates through `zipped_ages` and turns each pair into a key : value item.

    Print `names_to_ages` to see the result.

In [144]:
zipped_ages=zip(names,ages)
names_to_ages={key:value for key,value in zipped_ages}
print(names_to_ages)

{'Marina': 27, 'Vinay': 24, 'Connie': 43, 'Isaac': 35, 'Valentina': 52}


11. Use `.get()` to get the value of Marina's age and store it in a variable called `marina_age`. Use `None` as a default value if the key doesn't exist.

    Print `marina_age` with the following message:
    
    ```
    Marina's age is {marina_age}
    ```

In [149]:
marina_age=names_to_ages.get("Marina",None)
print("Marina's age is " + str(marina_age))

Marina's age is 27


### Using a Dictionary to Create a Medical Database

12. Let's create a third dictionary to represent a database of medical records that contains information such as a patient's name, age, sex, gender, BMI, number of children, smoker status, and insurance cost.

    First, create an empty dictionary called `medical_records`.

In [153]:
medical_records={}

13. Next, add `"Marina"` to `medical_records` as a key with the value being a dictionary of medical data:

    ```py
    {"Age": 27, "Sex": "Female", "BMI": 31.1, "Children": 2, "Smoker": "Non-smoker", "Insurance_cost": 6607.0}
    ```

In [156]:
medical_records["Marina"]={"Age": 27, "Sex": "Female", "BMI": 31.1, "Children": 2, "Smoker": "Non-smoker", "Insurance_cost": 6607.0}

14. Do the same for the following individuals:
    
    Name | Age | Sex | BMI | Children | Smoker | Insurance Cost
    --- | --- | --- | --- | --- | --- | ---
    Vinay | 24 | Male | 26.9 | 0 | Non-smoker | 3225.0
    Connie | 43 | Female | 25.3 | 3 | Non-smoker | 8886.0
    Isaac | 35 | Male | 20.6 | 4 | Smoker | 16444.0
    Valentina | 52 | Female | 18.7 | 1 | Non-smoker | 6420.0

In [159]:
medical_records["Vinay"]={"Age": 24, "Sex": "Male", "BMI": 26.9, "Children": 0, "Smoker": "Non-smoker", "Insurance_cost": 3225.0}
medical_records["Connie"]={"Age": 43, "Sex": "Female", "BMI": 25.3, "Children": 3, "Smoker": "Non-smoker", "Insurance_cost": 8886.0}
medical_records["Isaac"]={"Age": 35, "Sex": "Male", "BMI": 20.6, "Children": 4, "Smoker": "Smoker", "Insurance_cost": 16444.0}
medical_records["Valentina"]={"Age": 52, "Sex": "Female", "BMI": 18.7, "Children": 1, "Smoker": "Non-smoker", "Insurance_cost": 6420.0}

15. Print `medical_records` to see the result.

In [164]:
print(medical_records)

{'Marina': {'Age': 27, 'Sex': 'Female', 'BMI': 31.1, 'Children': 2, 'Smoker': 'Non-smoker', 'Insurance_cost': 6607.0}, 'Vinay': {'Age': 24, 'Sex': 'Male', 'BMI': 26.9, 'Children': 0, 'Smoker': 'Non-smoker', 'Insurance_cost': 3225.0}, 'Connie': {'Age': 43, 'Sex': 'Female', 'BMI': 25.3, 'Children': 3, 'Smoker': 'Non-smoker', 'Insurance_cost': 8886.0}, 'Isaac': {'Age': 35, 'Sex': 'Male', 'BMI': 20.6, 'Children': 4, 'Smoker': 'Smoker', 'Insurance_cost': 16444.0}, 'Valentina': {'Age': 52, 'Sex': 'Female', 'BMI': 18.7, 'Children': 1, 'Smoker': 'Non-smoker', 'Insurance_cost': 6420.0}}


16. The `medical_records` dictionary acts like a database of medical records. Let's access a specific piece of data in `medical_records`.

    Print out `Connie`'s insurance cost with the following message:
    
    ```
    Connie's insurance cost is X dollars.
    ```

In [167]:
print("Connie's insurance cost is {} dollars.".format(medical_records['Connie']['Insurance_cost']))

Connie's insurance cost is 8886.0 dollars.


17. `Vinay` has moved to a new country, and we no longer want to include him in our medical records.

    Remove `Vinay` from `medical_records`.

In [170]:
medical_records.pop("Vinay")

{'Age': 24,
 'Sex': 'Male',
 'BMI': 26.9,
 'Children': 0,
 'Smoker': 'Non-smoker',
 'Insurance_cost': 3225.0}

18. Let's take a closer look at each patient's medical record.

    Use a `for` loop to iterate through the items of `medical_records`. For each key-value pair, print out a string that looks like the following:
    
    ```
    {Name} is a {Age} year old {Sex} {Smoker} with a BMI of {BMI} and insurance cost of {Insurance_cost}
    ```

In [175]:
for key,value in medical_records.items():
  print("{} is a {} year old {} {} with a BMI of {} and insurance cost of {} ".format(key,value["Age"],value["Sex"],value["Smoker"],value["BMI"],value["Insurance_cost"]))

Marina is a 27 year old Female Non-smoker with a BMI of 31.1 and insurance cost of 6607.0 
Connie is a 43 year old Female Non-smoker with a BMI of 25.3 and insurance cost of 8886.0 
Isaac is a 35 year old Male Smoker with a BMI of 20.6 and insurance cost of 16444.0 
Valentina is a 52 year old Female Non-smoker with a BMI of 18.7 and insurance cost of 6420.0 
